// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
const HAS_CONFIGURED_SUPABASE = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Avoid hard-crashing the app when env vars are absent in hosted preview environments.
const FALLBACK_SUPABASE_URL = 'https://example.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'public-anon-key';
const HAS_NON_PLACEHOLDER_FALLBACK =
  FALLBACK_SUPABASE_URL !== 'https://example.supabase.co' &&
  FALLBACK_SUPABASE_PUBLISHABLE_KEY !== 'public-anon-key';
export const HAS_SUPABASE_CREDENTIALS = HAS_CONFIGURED_SUPABASE || HAS_NON_PLACEHOLDER_FALLBACK;

function resolveSupabaseUrl() {
  const configuredUrl = HAS_CONFIGURED_SUPABASE ? SUPABASE_URL! : FALLBACK_SUPABASE_URL;

  if (typeof window === "undefined") return configuredUrl;

  try {
    const parsed = new URL(configuredUrl);
    const localHosts = new Set(["127.0.0.1", "localhost"]);
    const browserHost = window.location.hostname;

    // In dev, allow pages opened via LAN/Tailscale IP to talk to the same host's local Supabase.
    if (import.meta.env.DEV && localHosts.has(parsed.hostname) && browserHost && !localHosts.has(browserHost)) {
      parsed.hostname = browserHost;
      return parsed.toString().replace(/\/$/, "");
    }
  } catch {
    // Ignore malformed URL parsing and fall back to configured value.
  }

  return configuredUrl;
}

export const RESOLVED_SUPABASE_URL = resolveSupabaseUrl();
const resolvedSupabasePublishableKey = HAS_CONFIGURED_SUPABASE
  ? SUPABASE_PUBLISHABLE_KEY!
  : FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(RESOLVED_SUPABASE_URL, resolvedSupabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// dev convenience: expose supabase in browser console
if (import.meta.env.DEV) (window as any).supabase = supabase;

if (!HAS_CONFIGURED_SUPABASE && typeof window !== 'undefined') {
  console.warn(
    '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Using fallback values so the UI can load.'
  );
}
