// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mapSupabaseUrl } from './resolveUrl';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
const HAS_CONFIGURED_SUPABASE = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Avoid hard-crashing the app when env vars are absent in hosted preview environments.
const FALLBACK_SUPABASE_URL = 'https://example.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'public-anon-key';
const HAS_NON_PLACEHOLDER_FALLBACK =
  FALLBACK_SUPABASE_URL !== 'https://example.supabase.co' &&
  FALLBACK_SUPABASE_PUBLISHABLE_KEY !== 'public-anon-key';
export const HAS_SUPABASE_CREDENTIALS = HAS_CONFIGURED_SUPABASE || HAS_NON_PLACEHOLDER_FALLBACK;

function resolveSupabaseUrl() {
  const configuredUrl = HAS_CONFIGURED_SUPABASE ? SUPABASE_URL! : FALLBACK_SUPABASE_URL;

  if (typeof window === "undefined") return configuredUrl;

  // Single home for the browser-facing URL mapping (localhost unchanged; ts.net → TLS :8443 API;
  // LAN/Tailscale-IP dev rewrite preserved). See resolveUrl.ts.
  return mapSupabaseUrl(configuredUrl, window.location.hostname, import.meta.env.DEV);
}

export const RESOLVED_SUPABASE_URL = resolveSupabaseUrl();
const resolvedSupabasePublishableKey = HAS_CONFIGURED_SUPABASE
  ? SUPABASE_PUBLISHABLE_KEY!
  : FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(RESOLVED_SUPABASE_URL, resolvedSupabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// dev convenience: expose supabase in browser console
if (import.meta.env.DEV) (window as any).supabase = supabase;

if (!HAS_CONFIGURED_SUPABASE && typeof window !== 'undefined') {
  console.warn(
    '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Using fallback values so the UI can load.'
  );
}
